name: Update Stats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Ensure up-to-date repository
      run: |
        git fetch --all
        git reset --hard origin/main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run stats.py
      run: |
        python stats.py

    - name: Configure Git
      run: |
        git config user.name "Whennya Stats"
        git config user.email "whennya@users.noreply.github.com"

    - name: Commit and Push Changes
      run: |
        git add README.MD
        git commit -m "Update README.MD Statistics" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
